<?php

namespace Database\Seeders;

use App\Models\Attendance;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AttendanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = User::all();
        $baseDate = Carbon::today();

        foreach ($users as $user) {
            $shift = $user->getEffectiveShift();
            
            // Seed 20 days of attendance for a more professional look
            for ($i = 0; $i < 20; $i++) {
                $currentDate = (clone $baseDate)->subDays($i);
                
                // Skip weekends (0=Sunday, 6=Saturday)
                if (in_array($currentDate->dayOfWeek, [0, 6])) continue;

                // 10% chance to be absent
                if (rand(1, 10) == 1) continue;

                $checkInOffset = rand(-10, 45); // Some arrive early, some late
                $checkOutOffset = rand(-15, 60);

                $startTime = $shift ? Carbon::parse($shift->start_time) : Carbon::parse('10:00:00');
                $endTime = $shift ? Carbon::parse($shift->end_time) : Carbon::parse('18:00:00');

                $checkIn = (clone $startTime)->addMinutes($checkInOffset);
                $checkOut = (clone $endTime)->addMinutes($checkOutOffset);

                $stayMinutes = $checkIn->diffInMinutes($checkOut);
                $lateMinutes = 0;
                $earlyLeavingMinutes = 0;
                $overtimeMinutes = 0;
                $status = 1; // Present

                if ($shift) {
                    // Late Calculation
                    if ($checkIn->gt($startTime)) {
                        $diff = $startTime->diffInMinutes($checkIn);
                        $lateMinutes = $diff;
                        if ($diff > $shift->late_threshold) {
                            $status = 2; // Late
                        }
                    }

                    // Early Leaving
                    if ($checkOut->lt($endTime)) {
                        $diff = $checkOut->diffInMinutes($endTime);
                        if ($diff > $shift->early_checkout_threshold) {
                            $earlyLeavingMinutes = $diff;
                        }
                    }

                    // Overtime
                    if ($checkOut->gt($endTime)) {
                        $overtimeMinutes = $endTime->diffInMinutes($checkOut);
                    }

                    // Deduct break
                    if ($stayMinutes > ($shift->break_time + 60)) {
                        $stayMinutes -= $shift->break_time;
                    }

                    // Half Day check
                    if ($stayMinutes < $shift->half_day_threshold) {
                        $status = 3; 
                    }
                }

                Attendance::create([
                    'user_id' => $user->id,
                    'shift_id' => $shift ? $shift->id : null,
                    'date' => $currentDate->toDateString(),
                    'check_in_time' => $checkIn->toTimeString(),
                    'check_out_time' => $checkOut->toTimeString(),
                    'check_in_ip' => '192.168.1.' . rand(1, 100),
                    'check_out_ip' => '192.168.1.' . rand(1, 100),
                    'device_info' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36',
                    'status' => $status,
                    'stay_minutes' => $stayMinutes,
                    'late_minutes' => $lateMinutes,
                    'early_leaving_minutes' => $earlyLeavingMinutes,
                    'overtime_minutes' => $overtimeMinutes,
                    'in_geofence' => true,
                    'notes' => 'Generated by seeder',
                ]);
            }
        }
    }
}
