@extends('backend.layouts.app')

@section('title', 'Payroll Generation - Purple Admin')

@section('content')
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
            <i class="mdi mdi-calculator"></i>                 
        </span> 
        Payroll Cycles
    </h3>
    <button type="button" class="btn btn-gradient-primary btn-sm" data-toggle="modal" data-target="#processPayroll">
        <i class="mdi mdi-play btn-icon-prepend"></i> Run New Payroll
    </button>
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card shadow-sm border-0">
            <div class="card-body text-center">
                @if($batches->isEmpty())
                <div class="py-5">
                    <img src="{{ asset('backend/assets/images/no-data.svg') }}" width="150" alt="No Data">
                    <h5 class="mt-3 text-muted">No Payroll cycles processed yet.</h5>
                </div>
                @else
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="bg-light text-center">
                            <tr>
                                <th>Cycle (Month/Year)</th>
                                <th>Generated By</th>
                                <th>Gross Total</th>
                                <th>Net Payable</th>
                                <th>Deductions</th>
                                <th>Status</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($batches as $batch)
                            <tr>
                                <td class="font-weight-bold">{{ date('F', mktime(0, 0, 0, $batch->month, 1)) }} {{ $batch->year }}</td>
                                <td>{{ $batch->processedBy->name ?? 'System' }}</td>
                                <td class="font-weight-bold text-success">{{ number_format($batch->total_gross, 2) }}</td>
                                <td class="font-weight-bold text-primary">{{ number_format($batch->total_net, 2) }}</td>
                                <td class="text-danger font-weight-bold">{{ number_format($batch->total_deductions, 2) }}</td>
                                <td>
                                    <label class="badge {{ $batch->status == 'paid' ? 'badge-gradient-success' : 'badge-gradient-warning' }}">
                                        {{ ucfirst($batch->status) }}
                                    </label>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('payroll.show', $batch->id) }}" class="btn btn-sm btn-outline-primary">
                                        <i class="mdi mdi-eye"></i> View Slips
                                    </a>
                                    <button class="btn btn-sm btn-outline-info" title="Print Report">
                                        <i class="mdi mdi-printer"></i>
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>

<!-- Process Payroll Modal -->
<div class="modal fade" id="processPayroll" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary text-white">
                <h5 class="modal-title">Generate Monthly Payroll</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('payroll.preview') }}" method="GET">
                <div class="modal-body text-left">
                    <div class="form-group">
                        <label>Select Month <span class="text-danger">*</span></label>
                        <select name="month" class="form-control" required>
                            @for($m=1; $m<=12; $m++)
                            <option value="{{ sprintf('%02d', $m) }}" {{ date('m') == $m ? 'selected' : '' }}>{{ date('F', mktime(0, 0, 0, $m, 1)) }}</option>
                            @endfor
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Select Year <span class="text-danger">*</span></label>
                        <select name="year" class="form-control" required>
                            @for($y=date('Y'); $y>=2020; $y--)
                            <option value="{{ $y }}">{{ $y }}</option>
                            @endfor
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-gradient-primary">Proceed to Preview</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
